---
title: "Proyecto TD 2022"
subtitle: Tratamiento de Datos. Grado en Ciencia de Datos- UV
author: "Olaf Meneses"
date:  "`r Sys.Date()`"
 
params:
  lang: ES
lang: "`r switch(params$lang, ES = 'es-ES', EN = 'en-US')`"
output:
  html_document:
    echo: yes
    number_sections: yes
    theme: lumen
    toc: yes
  pdf_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
  html_notebook:
    echo: yes
    number_sections: yes
    toc: yes
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    def: 'Definición '
    cor: 'Corolario '
    prp: 'Proposición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota: '
    solution: 'Solución. '
---


```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# CONFIGURACIÓN GENERAL
library(knitr)
options(width = 100)
# Opciones generales chunks
opts_chunk$set(echo=T,message = F, error = F, warning = F, comment = NA, 
               fig.align = 'center', dpi = 100, tidy = F, 
               cache.path = '.cache/', fig.path = './figure/')

#options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
#knit_hooks$set(plot = knitr:::hook_plot_html)
```

```{r, echo=F, include=F}
# Especificamos las librerías necesarias en esta lista

packages = c("knitr","tidyverse", "lubridate", "magrittr", "leaflet", "shiny",
             "shinythemes", "GGally", "forcats", "ggridges", "viridis", "naniar")

# Función que comprueba si tenemos instalado un paquete
# Si está instalado, lo carga
# Si no, lo instala y lo carga

package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

# Mostrar los paquetes cargados
search()

```
# Descarga de datos

```{r, include=F}
ids <- c("a54fb175-8013-460a-a2f0-22de7a210d7a", # Ponemos los ids para 
         "75a878a9-2bd9-4619-98ec-3224be867c65", # facilitar la descarga
         "6fa5210b-f9c7-47c8-9d1f-ddb7568f62de",
         "5a050cef-1107-4b3b-8e61-5daf5cfb2ca4",
         "e580f492-a2f6-4305-af24-f4c4d05b911c",
         "8058f1a5-c605-4baa-afff-2f638efb767f",
         "d842601d-35b4-4b88-96f7-42e8f68e1b74",
         "ea008906-e06a-4c72-9fe6-3238e212aae4",
         "64e4b7b4-e633-4753-b0ef-a57d785076f8",
         "ff8678b6-748e-4908-ab5b-9c7ff567da61",
         "b26d42ae-2be9-481a-9b79-71392d9e80bd",
         "1b41d86b-3939-488b-9035-92d851245924",
         "784f4732-abc5-41b1-857b-42decb306643",
         "3b2fe345-08fc-49d7-85c8-8cccf6a7e814")

names(ids) <- c("sueca_esq_denia", # Asociamos el nombre de la calle al id
                "cadiz16",
                "cadiz3",
                "cuba3",
                "sueca2",
                "sueca61",
                "sueca32",
                "carlescervera_reina",
                "salvador",
                "vivons",
                "carlescervera34",
                "puertorico21",
                "docserrano21",
                "gen_prim")

# Registramos la latitud y longitud de la posición de los sensores
latitude <- c(39.4628376,
              39.4631424,
              39.4640447,
              39.4628861,
              39.4633107,
              39.4605601,
              39.4613594,
              39.4613005,
              39.4635655, 
              39.4599927,
              39.4615883, 
              39.4609867,
              39.4626872,
              39.4625622)

longitude <- c(-0.37588849999997365,
              -0.3746647000000394,
              -0.3750515000000405,
              -0.3775977000000239,
              -0.3766378000000259,
              -0.37411520000000564,
              -0.37514680000003864,
              -0.37288599999999406,
              -0.37060220000000754,
              -0.3721407000000454,
              -0.3727962000000389,
              -0.3761412000000064,
              -0.3737806999999975,
              -0.370427100000029)

urls <- paste0("https://opendata.vlci.valencia.es/datastore/dump/", ids,
               "?format=csv&bom=true")

destfiles <- paste0("./data/", names(ids), ".csv")

# Descargamos los archivos
for(i in seq_along(urls)){
   download.file(urls[i], destfiles[i])
}
```
# Carga de datos

```{r}
# Asignamos a cada nombre de calle el dataframe que corresponde a sus datos.
for(i in seq_along(ids)){
  assign(names(ids)[i],
         read_csv(destfiles[i],
                  col_types = cols(dateObserved = col_date(format = "%Y-%m-%d"))) %>% 
           mutate(street = names(ids)[i],
                  latitude = latitude[i],
                  longitude = longitude[i]))
}

# Creamos un dataframe que reúna los datos de todas las calles
all_df <- bind_rows(sueca_esq_denia, cadiz16, cadiz3, cuba3, sueca2, sueca61, 
                    sueca32, carlescervera_reina, salvador, vivons, 
                    carlescervera34, puertorico21, docserrano21, gen_prim)

# Borramos los dataframes individuales que ya no necesitamos
rm(sueca_esq_denia, cadiz16, cadiz3, cuba3, sueca2, sueca61, 
   sueca32, carlescervera_reina, salvador, vivons, carlescervera34,
   puertorico21, docserrano21, gen_prim)
```

```{r}
# Seleccionamos las variables que nos interesan y transformamos a factor
# aquellas variables que deberían serlo.
all_df %<>%
  select(-`_id`:-entityType) %>% 
  mutate(entityId = factor(entityId),
         street = factor(street))

# Creamos un dataframe que incluya todas las fechas y que complete con NAs
# si el sensor de esa calle no registró los valores de esa fecha.
tidy_data <- all_df  %>% 
  arrange(dateObserved) %>% 
  complete(dateObserved, nesting(street, entityId, latitude, longitude))

# Visualizamos los datos faltantes
vis_miss(tidy_data)
# Observamos que de los registros que faltan, todas las variables relacionadas con el sonido están incompletas. Esto quiere decir que hay días en los que algunos sensores no han hecho ningún registro. Asimismo, para los días que hay registro, todas las variables están completas.

# Tabla que muestra la calle donde se sitúa el sensor y la cantidad de días
# sin datos registrados
tidy_data %>% 
  filter(is.na(LAeq)) %>% 
  count(street) %>%
  ggplot(aes(x = fct_reorder(street, n), n)) +
  geom_col() +
  geom_text(aes(label = n), vjust = -0.5, size = 4) + 
  coord_cartesian(ylim = c(-5, 190)) +
  labs(x = "Calle", y = "Registros faltantes", 
       title = "Número de registros faltantes por sensor") +
  theme(axis.text.x = element_text(hjust = 0.5, vjust = 0.5, angle=90))

# Gráfico que muestra los valores de LAeq (en azul) según la fecha para cada calle
# y en rojo los días que no hubo registro.
ggplot(tidy_data,
       aes(x = dateObserved,
           y = LAeq)) +
 geom_miss_point(alpha = 0.4) +
 facet_wrap(~street) +
  labs(x = "Fecha", title = "Datos faltantes en cada sensor") +
  theme(axis.text.x = element_text(hjust = 0.5, vjust = 0.5, angle=90)) +
  scale_color_discrete(name = "Datos faltantes", labels = c("Faltante", "No Faltante"))
```